--------------------------------------------------------
--  Arquivo criado - Segunda-feira-Novembro-12-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CAR
--------------------------------------------------------

  CREATE TABLE "C##MCM"."CAR" 
   (	"ID" NUMBER(*,0), 
	"BRAND" VARCHAR2(100 BYTE), 
	"ANO" NUMBER, 
	"ID_COLOR" NUMBER(*,0), 
	"PRICE" NUMBER, 
	"SALE_DATE" DATE, 
	"STATUS" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COLOR
--------------------------------------------------------

  CREATE TABLE "C##MCM"."COLOR" 
   (	"ID" NUMBER(*,0), 
	"NOME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "C##MCM"."USUARIO" 
   (	"ID" NUMBER(*,0), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"PERFIL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence CAR_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##MCM"."CAR_SQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 17 NOCACHE  NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence COLOR_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##MCM"."COLOR_SQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7 NOCACHE  NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence USER_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##MCM"."USER_SQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE   ;
REM INSERTING into C##MCM.CAR
SET DEFINE OFF;
Insert into C##MCM.CAR (ID,BRAND,ANO,ID_COLOR,PRICE,SALE_DATE,STATUS) values ('1','VW','2012','1','10000',to_date('01/01/18','DD/MM/RR'),'P');
Insert into C##MCM.CAR (ID,BRAND,ANO,ID_COLOR,PRICE,SALE_DATE,STATUS) values ('2','Audi','2013','2','11000',to_date('02/01/18','DD/MM/RR'),'S');
Insert into C##MCM.CAR (ID,BRAND,ANO,ID_COLOR,PRICE,SALE_DATE,STATUS) values ('3','Renault','2014','3','12000',to_date('03/01/18','DD/MM/RR'),'P');
Insert into C##MCM.CAR (ID,BRAND,ANO,ID_COLOR,PRICE,SALE_DATE,STATUS) values ('4','BMW','2015','4','13000',to_date('04/01/18','DD/MM/RR'),'B');
Insert into C##MCM.CAR (ID,BRAND,ANO,ID_COLOR,PRICE,SALE_DATE,STATUS) values ('5','Mercedes','2016','5','14000',to_date('05/01/18','DD/MM/RR'),'S');
Insert into C##MCM.CAR (ID,BRAND,ANO,ID_COLOR,PRICE,SALE_DATE,STATUS) values ('6','Volvo','2017','6','15000',to_date('06/01/18','DD/MM/RR'),'P');
Insert into C##MCM.CAR (ID,BRAND,ANO,ID_COLOR,PRICE,SALE_DATE,STATUS) values ('7','Honda','2018','1','16000',to_date('07/01/18','DD/MM/RR'),'B');
Insert into C##MCM.CAR (ID,BRAND,ANO,ID_COLOR,PRICE,SALE_DATE,STATUS) values ('8','Jaguar','2019','2','17000',to_date('08/01/18','DD/MM/RR'),'S');
Insert into C##MCM.CAR (ID,BRAND,ANO,ID_COLOR,PRICE,SALE_DATE,STATUS) values ('9','Ford','2020','3','18000',to_date('09/01/18','DD/MM/RR'),'P');
Insert into C##MCM.CAR (ID,BRAND,ANO,ID_COLOR,PRICE,SALE_DATE,STATUS) values ('10','Fiat','2021','4','19000',to_date('10/01/18','DD/MM/RR'),'B');
Insert into C##MCM.CAR (ID,BRAND,ANO,ID_COLOR,PRICE,SALE_DATE,STATUS) values ('16','AAAAAAAAAAAAAA','222222','2','222222',to_date('11/03/20','DD/MM/RR'),'S');
REM INSERTING into C##MCM.COLOR
SET DEFINE OFF;
Insert into C##MCM.COLOR (ID,NOME) values ('1','Orange');
Insert into C##MCM.COLOR (ID,NOME) values ('2','Black');
Insert into C##MCM.COLOR (ID,NOME) values ('3','Gray');
Insert into C##MCM.COLOR (ID,NOME) values ('4','Blue');
Insert into C##MCM.COLOR (ID,NOME) values ('5','Yellow');
Insert into C##MCM.COLOR (ID,NOME) values ('6','Red');
REM INSERTING into C##MCM.USUARIO
SET DEFINE OFF;
Insert into C##MCM.USUARIO (ID,EMAIL,PASSWORD,PERFIL) values ('1','admin@helpdesk.com','$2a$10$qUU8yaDD4.JGTXzDj.G1Z.c8Gb0KYfXA4Qk/SixA.PnAE1GVrykhu','0');
Insert into C##MCM.USUARIO (ID,EMAIL,PASSWORD,PERFIL) values ('2','custumer@helpdesk.com','$2a$10$8lAC1uDRhLci6tSl7W9MDOkEC.peDrDsD.ImnHidx7KrFPepHakn6','1');
--------------------------------------------------------
--  DDL for Index COLOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MCM"."COLOR_PK" ON "C##MCM"."COLOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MCM"."USER_PK" ON "C##MCM"."USUARIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USER_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MCM"."USER_UN" ON "C##MCM"."USUARIO" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CAR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MCM"."CAR_PK" ON "C##MCM"."CAR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--------------------------------------------------------
--  Constraints for Table CAR
--------------------------------------------------------

  ALTER TABLE "C##MCM"."CAR" ADD CONSTRAINT "CAR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COLOR
--------------------------------------------------------

  ALTER TABLE "C##MCM"."COLOR" ADD CONSTRAINT "COLOR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "C##MCM"."COLOR" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "C##MCM"."COLOR" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "C##MCM"."USUARIO" ADD CONSTRAINT "USER_UN" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "C##MCM"."USUARIO" ADD CONSTRAINT "USER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "C##MCM"."USUARIO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CAR
--------------------------------------------------------

  ALTER TABLE "C##MCM"."CAR" ADD CONSTRAINT "CAR_COLOR_FK" FOREIGN KEY ("ID_COLOR")
	  REFERENCES "C##MCM"."COLOR" ("ID") ENABLE;
